package com.tanis138.cardealer.menu;

public enum MenuId {
    MAIN,
    WAREHOUSE, WAREHOUSE_LIST, WAREHOUSE_GENERATE, WAREHOUSE_ADD, WAREHOUSE_DELETE, WAREHOUSE_ADD_CAR, WAREHOUSE_DELETE_CAR,
    ALL_CARS, ALL_CARS_LIST_ALL, ALL_CARS_LIST_BRAND, ALL_CARS_LIST_MODEL, ALL_CARS_LIST_PETROL, ALL_CARS_LIST_DIESEL,
    ALL_CARS_LIST_AT, ALL_CARS_LIST_MT, ALL_CARS_LIST_IDENTICAL,
    NEW_CARS, NEW_CARS_LIST_ALL, NEW_CARS_LIST_BRAND, NEW_CARS_LIST_MODEL, NEW_CARS_LIST_PETROL, NEW_CARS_LIST_DIESEL,
    NEW_CARS_LIST_AT, NEW_CARS_LIST_MT, NEW_CARS_LIST_IDENTICAL,
    USED_CARS, USED_CARS_LIST_ALL, USED_CARS_LIST_BRAND, USED_CARS_LIST_MODEL, USED_CARS_LIST_PETROL, USED_CARS_LIST_DIESEL,
    USED_CARS_LIST_AT, USED_CARS_LIST_MT,
}
